SELECT WORKER_ID, COUNT(PROJECT_ID)
FROM PROJECT_WORKER  GROUP BY WORKER_ID 
HAVING COUNT (WORKER_ID)=( 
SELECT MAX(PROJECT_ID) 
FROM ( 
SELECT WORKER_ID, COUNT(WORKER_ID) PROJECT_ID 
FROM PROJECT_WORKER 
GROUP BY WORKER_ID));