SELECT 'YOUNGEST' as TYPE, NAME , BIRTHDAY 
FROM WORKER 
WHERE BIRTHDAY = (SELECT max(BIRTHDAY ) FROM WORKER )
UNION ALL 
SELECT 'ELDEST' AS TYPE, NAME ,BIRTHDAY 
FROM WORKER 
WHERE BIRTHDAY = (SELECT min(BIRTHDAY ) FROM WORKER );